[package]
name = "collator-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
subxt = "0.50.1"
sp-core = "38"
sp-crypto-hashing = "0.1"
parity-scale-codec = { version = "3", features = ["derive"] }